name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - preproduction
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON}}
      PLATFORM_DATABASE: ${{secrets.PLATFORM_DATABASE}}
      USERS_TABLE: ${{secrets.USERS_TABLE}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      - name: Clear npm cache
        run: npm cache clean --force
        working-directory: node-server
      
      - name: Install dependencies
        run: npm install
        working-directory: node-server

      - name: Run tests
        id: test
        run: npm test
        working-directory: node-server

      - name: Stop the server
        run: |
          pid=$(lsof -ti :3001)
          if [ -n "$pid" ]; then
            kill $pid
          fi
        if: always()

      - name: Build project
        run: |
          npm run start
      
          sleep 5
          
          sudo kill -9 $(sudo lsof -t -i:3001)
        working-directory: node-server
        if: steps.test.outcome == 'success'

      - name: Deploy to production
        if: (github.ref == 'refs/heads/production') && (steps.test.outcome == 'success')
        run: |
          echo "production"